{% set name = "pyannote.core" %}
{% set version = "4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyannote.core-{{ version }}.tar.gz
  sha256: f8321402763d64474fad6a0761fc2f237e54395dc24104f0face4b8678fa32ec

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - dataclasses >=0.7  # [py<37]
    - matplotlib-base >=2.0.0
    - numpy >=1.10.4
    - pandas >=0.17.1
    - python
    - scipy >=1.1
    - simplejson >=3.8.1
    - sortedcontainers >=2.0.4
    - typing-extensions >=3.7.4.1

test:
  imports:
    - pyannote
    - pyannote.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pyannote.github.io/
  summary: Advanced data structures for handling temporal segments with attached labels.
  doc_url: https://pythonhosted.org/pyannote.core/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tyrius02
